document.addEventListener("DOMContentLoaded", function() {

    // --- 1. Lógica de Mensajes Diarios ---
    
    // ¡¡AQUÍ PONES TUS MENSAJES!!
    // Agrega tantos como quieras.
    const mensajes = [
        "¡Espero que tengas un día tan increíble como tú mi bonitaaaaa! ❤️", // Día 1
        "Un recordatorio: Eres lo mejor que me ha pasado en toda la vida.", // Día 2
        "Recuerda que te amo con todo mi corazoncitooooooo", // Día 3
        "Gracias por todas las risas, ¡Eres mi persona favorita!", // Día 4
        "Si sientes que tu dia va mal, no dudes en hablarme, que voy a estar para esucharte.", // Día 5
        "No importa qué pase, estoy aquí para ti. Siempre. 💖", // Día 6
        "Eres mi potito coxino supremooooooo wuajajaja", // Día 7
        "Eres mi sol en los días grises.",
        "Me encanta el futuro que estamos construyendo.",
        "Pienso en ti y se me arregla el día.",
        "Recuerda potito: yo tengo el poto mas limpio que tuuuuu wuajajaja",
        "Siempre estare de tu lado, pase lo que pase",
        "Ubuntu.",
        "Mi vida esta completa desde que tú estas en ella.",
        "Te quiero a tí y nadie más.",
        "Que hoy te sientas tan amada como yo te amo.",
        "Eres elocuente. Me encanta cómo hablas y te expresas.",
        "Eres mi 'te amo' favorito.",
        "Amo tu estilo. Tienes una onda que me mata.",
        "Admiro tu disciplina. Eres sequísima.",
        "¡Vamos con todo hoy! Eres seca.",
        "Gracias por ser mi lugar seguro.",
        "¡Buenos días, sol de mi vida! Gracias por iluminar mis días.",
        "Amo lo curiosa que eres, siempre aprendiendo algo nuevo.",
        "¡Vamos! ¡Demuéstrales a todos de qué estás hecha!",
        "Eres mi persona favorita y la más capaz que conozco.",
        "Me haces feliz. Así de simple.",
        "Eres mi notificación favorita. Te amo.",
        "Lo nuestro es mi historia de amor favorita.",
        "Mi amor por ti es incondicional.",
        "Que la noche te traiga paz y descanso. Buenas noches, amor.",
        "Me encanta la vida que estamos creando.",
        "Eres mi número 1.",
        "Mi corazón te eligió. Y no se equivocó. Te amo.",
        "Pst... ¡me encantas!",
        "Eres mi ídola. En serio.",
        "Me encanta lo auténtica que eres. Nunca tratas de ser alguien más.",
        "Eres mi notificación favorita.",
        "Si te digo 'te amo', es porque lo siento en cada rincón de mi ser.",
        "Te amo. (Por si se te había olvidado).",
        "Gracias por ser, simplemente, inolvidable.",
        "Amo tu ternura. Eres mi lugar feliz.",
        "¡Vamos, mi campeona! Tú puedes.",
        "Te amo, te amo, te amo. ¿Quedó claro? ❤️",
        "https://open.spotify.com/intl-es/track/3ydweVPwq9PCEVJ8WwqT6u?si=94a77b2982ba47e6",
        "¡Qué suerte la mía de tenerte!",
        "Tu sonrisa tiene el poder de arreglar cualquier día malo.",
        "Contigo, el 'felices para siempre' es una realidad diaria.",
        "Eres la persona más divertida que conozco.",
        "Amo lo cariñosa que eres. Tus abrazos reinician mi vida.",
        "¡Arriba, dormilona! Te envío un beso de buenos días.",
        "Eres mi todo.",
        "Aprecio tu honestidad y tu lealtad.",
        "Buenos días. Solo quería ser la primera persona en saludarte hoy.",
        "Eres mi razón de sonreír.",
        "Amo lo mucho como me tratas y me haces sentir..",
        "Mi mundo es mejor porque tú estás en él. Te amo.",
        "Gracias por ser mi refugio y mi paz.",
        "Eres mi persona. ❤️",
        "Que la suerte te acompañe hoy... ¡aunque ya la tienes conmigo! 😉 Lindo día.",
        "Buenos días, mi corazón. ¿Ya te dije que te amo hoy?",
        "Gracias por elegirme cada día.",
        "Gracias por ser mi equilibrio perfecto.",
        "Me encanta lo descomplicada que eres.",
        "Fin del día. Misión cumplida. Hora de soñar. Te amo.",
        "Eres hermosa por fuera, pero tu interior es una obra de arte.",
        "Te amo. En letras grandes, con mayúsculas y con fuegos artificiales.",
        "Te amo. Y me encanta que seas tú.",
        "Gracias por ser mi cable a tierra.",
        "¡Hoy será un gran día! Lo sé porque estás en él.",
        "Gracias por ser mi cómplice número uno.",
        "Contigo, la vida es una aventura constante.",
        "Me encanta que nos entendamos con solo mirarnos.",
        "¡Hoy va a ser un día 10/10! ¡Confía! Te amo.",
        "¡Qué suerte la mía! en tener una noviesita tan pero tan hermosaaaaa",
        "¡Un cafecito y a brillar, mi vida! Buenos días.",
        "Gracias por este día. Ahora a soñar. Te amo.",
        "Buenos días a la mujer más hermosa del universo.",
        "No importa qué tan gris esté el día, tú brillas más.",
        "Gracias por tu paciencia, tu luz y tu amor.",
        "Aprecio tu esfuerzo y todo lo que haces.",
        "Te amo por encima de todo.",
        "Mi corazón te pertenece. (Cuídalo).",
        "Eres mi sol en los días grises. ☀️",
        "No quiero una vida perfecta, te quiero a ti. Y eso la hace perfecta.",
        "Te amo. Y te admiro más todavía.",
        "Mi corazón está lleno de gratitud por ti.",
        "Te amo. Y me encanta.",
        "Que tu día sea tan dulce como tus besos.",
        "Te amo de aquí a la luna, a pasitos de tortuga (para que dure más jejeejjeje).",
        "No te estreses. Todo tiene solución. Y si no, nos reímos del problema y lo resolvemos juntos",
        "Te elijo a ti. Hoy y todos los días.",
        "Me encanta tu carita bonitaaaaaa.",
        "Gracias por ser mi lugar seguro.",
        "https://open.spotify.com/intl-es/track/5frMgt4jqRGJk3yMKfqOyl?si=107cb11f947842c8",
        "Eres la pieza que le faltaba a mi rompecabezas. Te amo.",
        "Prometo cuidarte, respetarte y amarte todos los días.",
        "Amo tu risa. Es mi sonido favorito en todo el mundo.",
        "Gracias por creer en mí, incluso cuando yo no lo hago.",
        "¡Buenos días, mi amor! Espero que tengas un día tan increíble como tú.",
        "Contigo quiero ir a todas partes.",
        "sen^2(Tú) + cos^2(Yo) = 1.",
        "Tu energía es contagiosa. ¡Me encanta!",
        "Hoy es un nuevo día para intentarlo. ¡Con todo!",
        "Eres mi vicio.",
        "Si necesitas un 'break', tómalo. Te espero con regaloneo.",
        "¡Fuerza, mi amor! Esta semana es tuya, dale con todo potitoooo.",
        "Tú y yo contra el mundo. Siempre.",
        "Eres mi amor, mi cómplice, mi todo.",
        "Tú tienes el poder de hacer de este un gran día.",
        "Tu pasión por lo que haces es inspiradora.",
        "¡Lindo despertar, amor mío!",
        "Eres el amor de mi vida. Y no me canso de decírtelo.",
        "No te presiones de más. Haz lo que puedas, y eso está perfecto.",
        "No puedo sacarte de mi cabeza. (Ni quiero).",
        "Cierra los ojos, amor. Mañana nos espera. Buenas noches.",
        "No importa qué tan difícil sea el día, saber que te veré lo hace todo mejor. Lindo día.",
        "Contigo aprendí lo que es el amor de verdad.",
        "Eres mi sol. ☀️",
        "Que tengas un día maravilloso. No dejes de sonreír. Te amo.",
        "Eres mi guerrera. ¡No hay nada que no puedas superar!",
        "Aprecio cada pequeño detalle que haces por mí.",
        "https://open.spotify.com/intl-es/track/3lGMtkONrZdJ8kTCg6KIFf?si=457469fb86654231",
        "Hagamos que 'para siempre' suene a poco.",
        "Tu inteligencia me enamora cada día más.",
        "Mi felicidad tiene tu nombre. Te amo.",
        "Aprecio tu forma de ver el mundo. Me inspiras.",
        "Tengo tantos planes para nosotros... y todos son increíbles.",
        "Gracias por todas las risas. Eres increíble.",
        "Eres mi gusto culposo (y no culposo también).",
        "Eres increíblemente talentosa. No lo dudes.",
        "Amo la familia que estamos formando.",
        "Me encanta la paz que me da nuestra relación.",
        "Amo el equipo que somos. Juntos somos invencibles.",
        "Me veo viejo y feliz a tu lado.",
        "Eres una mujer increíble. Que nadie te diga lo contrario.",
        "Me encanta lo decidida que eres. Vas por lo que quieres.",
        "Nuestro amor puede con todo.",
        "Admiro tu capacidad de ver lo bueno en las personas.",
        "Pienso en ti. (Todo el rato).",
        "Gracias por ser mi compañera de vida.",
        "https://open.spotify.com/intl-es/track/2oGcLhbdlhz7EOwIqcLTcJ?si=8a814cd10fc74537",
        "Gracias por ser mi aventura favorita.",
        "Admiro tu lealtad. Eres la mejor compañera.",
        "Gracias por llenar mi vida de colores.",
        "No hay nadie más con quien prefiera pasar mi tiempo.",
        "Aprecio que me dejes ser yo mismo contigo.",
        "Soy tan afortunado de tenerte. Gracias por ser tú.",
        "Mi plan favorito: amarte todos los días.",
        "Eres mi todo.",
        "Confío en ti y en tu capacidad. ¡Vas a lograrlo siosi!",
        "Agradezco a la vida por ponerte en mi camino.",
        "Tú puedes con todo. ¡Y yo estoy a tu lado para aplaudirte!",
        "Te amo. Gracias por dejarme amarte.",
        "Cree en ti. Yo creo en ti ciegamente.",
        "Gracias por ser la banda sonora de mi vida.",
        "Me encanta nuestra historia. Y lo mejor es que aún se está escribiendo.",
        "Gracias por ser tan tú. Tan única. Tan perfecta.",
        "Eres mi socia, mi amiga, mi amante. Mi todo.",
        "Amo nuestras tonterías.",
        "Duerme bien, mi vida. Estoy aquí cuidando tus sueños.",
        "Contigo, todo. Sin ti, nada.",
        "¡Me gané la lotería contigo!",
        "Gracias por amarme así. Te amo.",
        "Mi lugar favorito en el mundo es a tu lado.",
        "Siento que contigo puedo ser yo mismo. Y eso no tiene precio.",
        "Me encanta lo mucho que te esfuerzas por tus metas.",
        "Estoy orgullosísimo de todo lo que has logrado.",
        "Eres la persona más capaz que conozco.",
        "Amo como eres.",
        "Te amo. Y punto.",
        "Mi mundo es mejor contigo en él.",
        "Eres mi definición perfecta de amor.",
        "Que tengas dulces sueños y un despertar lleno de energía.",
        "Admiro tu paciencia (especialmente conmigo).",
        "Agradezco tener a la mejor polola del mundo. (y eres tuuuuuuu).",
        "Lo nuestro es mi cosa favorita.",
        "Eres más fuerte de lo que crees. ¡Ve a comerte el mundo!",
        "Te amo. Con tus virtudes, tus defectos, tus mañas y tu risa.",
        "Tu voz me da paz. Podría escucharte hablar por horas.",
        "https://open.spotify.com/intl-es/track/7sRXhReWmJF5pqyg3uUTES?si=e075e549602a40ef",
        "Gracias por ser la luz al final del túnel.",
        "Te envío un beso gigante de buenas noches. Que llegue hasta donde estés.",
        "Me encanta planear el futuro contigo. Todo suena mejor si estás tú.",
        "Si mi amor por ti tuviera contador, ya habría roto la máquina.",
        "Aprecio el equipo que formamos.",
        "Lo nuestro es de película.",
        "Holi yo te amo mucho más de lo que tu me amas ejejeejej",
        "Gracias por ser mi mejor amiga y mi polola, todo en uno.",
        "Eres mi notificación favorita.",
        "Mi corazón late a tu ritmo. Te amo.",
        "Cierra los ojos y respira. Todo estará bien. Te lo prometo.",
        "No puedo esperar a ver qué nos espera en el futuro. Juntitos.",
        "Gracias por cada sonrisa que me sacas.",
        "Te amo. Fin del comunicado.",
        "No sé qué hice para merecerte, pero gracias.",
        "Soy tuyo para siempre.",
        "Nunca dudes lo hermosa y perfecta que eres mi linda.",
        "Te amo preciosaaaaa",
        "Mi amor por ti es gigante.",
        "https://open.spotify.com/intl-es/track/12NW2sUhBFz5VUxDZTp3Op?si=3b0c0f1564d24845",
        "Te quiero. Pa siempre.",
        "Tu forma de ser me motiva. ¡Vamos por más!",
        "Soy un mejor hombre gracias a ti.",
        "Gracias por ser mi compañera de aventuras. Que vengan mil más.",
        "Respira. Estoy orgulloso de ti, pase lo que pase.",
        "Eres mi paz.",
        "Holi amorcito, en esta aplicacion veras un mensajito distinto a diario jijijij, de vdd spero que te guste. El primer mensaje es: Siempre recuerda lo mucho que te amo mi vida.",
        "Me encanta que nos propongamos crecer juntos.",
        "Mi amor por ti es más grande que ayer y menos que mañana.",
        "Te amo. Así de simple. Así de complejo. Así de verdad.",
        "Me encanta lo linda que te ves siempre.",
        "Admiro tu fuerza más de lo que imaginas.",
        "Sigamos sumando recuerdos inolvidables.",
        "Te amo. Hoy, mañana y siempre.",
        "Nunca dejes de ser esa persona increíblemente bondadosa.",
        "¡Pienso en ti en cada momento del diaaaaa!",
        "Eres mi casualidad más bonita. Te amo.",
        "Gracias por las conversaciones profundas y las tonterías.",
        "¡Vas a brillar hoy! No tengo dudas.",
        "Te amo. En todas tus versiones. En todos tus días.",
        "Gracias por ser el 'sí' a todas mis preguntas.",
        "Para lo que necesites, a la hora que sea. Cuenta conmigo.",
        "Te amo, mi hermosa. Más de lo que imaginas.",
        "Me encanta ser 'nosotros'.",
        "Que tu día esté lleno de momentos que te hagan feliz.",
        "Amo tus ojos. Me pierdo en ellos.",
        "Eres mágica.",
        "No estás sola en esto. Estamos juntos.",
        "Que tengas un día lindo. Ahora, a descansar. Te amo.",
        "Agradezco cada segundo que paso contigo.",
        "Mi amor por ti no tiene fecha de vencimiento.",
        "Lo estás haciendo increíble. Sigue adelante.",
        "Pase lo que pase hoy, recuerda que te amo y te admiro.",
        "Me gustas más que el feriado.",
        "Gracias por ser mi fan #1. Yo soy el tuyo.",
        "https://open.spotify.com/intl-es/track/1gQxoBZiyLK5hRLLoBg89x?si=0ea9e71de10b4984.",
        "Eres mi futuro.",
        "Tienes un 'no sé qué' que me tiene loco.",
        "Lo nuestro es real. Y es lo mejor que tengo.",
        "Gracias por enseñarme tanto sobre el amor.",
        "¡Hoy es tu día! ¡Aprovéchalo!",
        "Mi corazón es tuyo. Hoy y siempre.",
        "Me encanta tu inteligencia y tu corazón.",
        "Mi lugar favorito para terminar el día es en tus pensamientos. Buenas noches.",
        "https://open.spotify.com/intl-es/track/7dITAq1YP5e0kTcaDq4YWI?si=e413499f980140d9",
        "Tienes un corazón de oro.",
        "¡Ánimo, mi amor! Todo saldrá bien.",
        "No puedo esperar a ver qué nos espera en el futuro. Juntitos.",
        "Tu esfuerzo valdrá la pena. ¡Sigue así!",
        "Gracias por ser tan maravillosamente tú.",
        "Te amo. No lo dudes ni por un segundo.",
        "Mi destino favorito es estar contigo. Te amo.",
        "Eres mi calma en medio del caos.",
        "Amo la conexión que tenemos.",
        "Que la vida nos encuentre siempre juntos.",
        "Eres mi hogar. Donde estés tú, ahí estoy bien.",
        "Eres luz pura, mi amor.",
        "¡Me encantas! De aquí al infinito.",
        "Eres mi presente y mi futuro.",
        "Somos. Y muchoooooooooo.",
        "Oye. Sí, tú. Eres hermosa. Sigue con lo tuyo.",
        "Cada día contigo es mi 'para siempre' favorito.",
        "Eres valiente. Más de lo que crees.",
        "Eres mi lugar feliz.",
        "Me encanta tu forma de ser.",
        "Admiro tu fuerza.",
        "Eres mi momento favoritodel dia.",
        "https://open.spotify.com/intl-es/track/0q6LuUqGLUiCPP1cbdwFs3?si=d0622ea4f8114219",
        "Agradezco cada momento contigo.",
        "Que hoy te pase todo lo bonito que mereces. Te amo.",
        "Estoy enviándote toda mi energía positiva. ¡Tú puedes!",
        "Tu voz me da paz. Podría escucharte hablar por horas.",
        "Me encanta tu forma de ser. Nunca la pierdas.",
        "Gracias por ser la luz al final del túnel.",
        "Te envío un beso gigante de buenos dias. Que llegue hasta donde estés.",
        "Me encanta planear el futuro contigo. Todo suena mejor si estás tú.",
        "Si mi amor por ti tuviera contador, ya habría roto la máquina.",
        "Aprecio el equipo que formamos.",
        "Lo nuestro es de película.",
        "Que nada te quite la paz. Y si algo lo hace, me avisas y le pego. jejejejej",
        "Gracias por ser mi potito, mi novia y mi poto loko, todo en uno.",
        "Eres mi notificación favorita.",
        "Mi corazón late a tu ritmo. Te amo.",
        "Cierra los ojos y respira. Todo estará bien. Te lo prometo.",
        "Podría mirarte por horas y no aburrirme.",
        "Gracias por cada sonrisa que me sacas.",
        "Te amo. Fin del comunicado.",
        "No sé qué hice para merecerte, pero gracias.",
        "Te envío un abrazo virtual de esos que aprietan fuerte. ¡Tú puedes!",
        "Mi sonrisa te pertenece.",
        "Estoy aquí para lo bueno, lo malo y lo feo. Te amo.",
        "¡Me encantas mucho muchoooooo!",
        "Mi corazón hace boom por ti.",
        "https://open.spotify.com/intl-es/track/5hMadRUTp4S3ewaJIaI7Qo?si=80a8a15efd604d7c",
        "Te quiero. Pa' siempre.",
        "Soy un mejor hombre gracias a ti.",
        "Gracias por ser mi compañera de aventuras. Que vengan mil más.",
        "Estoy orgulloso de ti mi vida.",
        "Eres mi paz.",
        "Amo tu forma única de ver el mundo, y lo perfecta e hermosa que eres.",
        "Me encanta que nos apoyemos mutuamente a crecer.",
        "Mi amor por ti es más grande que ayer y menos que mañana.",
        "Te amo. Así de simple. Así de complejo. Así de verdad.",
        "Me encanta lo bien que hueles siempre.",
        "te admiro más de lo que imaginas.",
        "Sigamos sumando recuerdos inolvidables.",
        "Te amo. Hoy, mañana y siempre.",
        "Nunca dejes de ser esa persona increíblemente genial y brillante.",
        "Despierta, mi vida. Es hora de brillar. ¡Pienso en ti!",
        "Eres mi casualidad más bonita. Te amo.",
        "Gracias por las conversaciones profundas y las tonterías.",
        "¡Vas a brillar hoy! No tengo dudas.",
        "Te amo. En todas tus versiones. En todos tus días.",
        "Amo la forma en como eres, porque eres perfecta.",
        "Gracias por ser el 'sí' a todas mis preguntas.",
        "Para lo que necesites, a la hora que sea. Cuenta conmigo.",
        "Te amo, mi bonita. Más de lo que imaginas.",
        "Me encanta ser 'nosotros'.",
        "Que tu día esté lleno de momentos que te hagan feliz.",
        "Amo tus ojos, tanto que me pierdo en ellos.",
        "Eres mágica.",
        "Poto coxino te amooooooo",
        "No estás sola en esto. Estamos juntos.",
        "Agradezco cada segundo que paso contigo.",
        "Mi amor por ti no tiene fecha de vencimiento.",
        "Lo estás haciendo increíble. Sigue adelante.",
        "Pase lo que pase hoy, recuerda que te amo y te admiro.",
        "Me gustas más que el pan con chancho.",
        "Gracias por ser mi fan #1. Yo soy el tuyo.",
        "No puedo esperar a formar una familia juntos.",
        "Eres mi 14/02.",
        "Tienes un 'no sé qué' que me tiene loco.",
        "Lo nuestro es real. Y es lo mejor que tengo.",
        "Gracias por enseñarme tanto sobre el amor.",
        "¡Hoy es tu día! ¡Aprovéchalo!",
        "Mi corazón es tuyo. Hoy y siempre.",
        "Me encanta lo inteligente y tu corazón.",
        "https://open.spotify.com/intl-es/track/1ShyiEm2kD0XMA7fNhMIVk?si=cc9c70db5eca47c0",
        "¡Ánimo, mi amor! Todo saldrá bien.",
        "No puedo esperar a ver qué nos depara el futuro. Juntos.",
        "Tu esfuerzo valdrá la pena. ¡Sigue así!",
        "Gracias por ser tan maravillosamente tú.",
        "Te amo. No lo dudes ni por un segundo.",
        "Mi destino favorito es estar contigo. Te amoooooooo.",
        "Eres mi calma en medio del caos.",
        "Si te caes, aquí estoy para levantarte (o para tirarme contigo un rato) jajajajaj.",
        "Amo la conexión que tenemos.",
        "Que la vida nos encuentre siempre juntos.",
        "Eres mi hogar. Donde estés tú, ahí estoy bien.",
        "Me encanta lo tan buena persona que eres mi vida.",
        "Eres luz pura, mi amor.",
        "¡Me encantas! De aquí al infinito.",
        "Eres mi presente y mi futuro.",
        "Somos la mejor pareja del mundo.",
        "Cada día contigo es mi 'para siempre' favorito.",
        "Eres valiente. Más de lo que crees.",
        "Eres mi lugar feliz.",
        "Me encanta tu forma de ser.",
        "Admiro tu fuerza.",
        "https://open.spotify.com/intl-es/track/7zpNN01FLMP70EYGcxCCDY?si=3af2a9649de04a15",
        "Agradezco cada momento contigo.",
        "Que hoy te pase todo lo bonito que mereces. Te amo.",
        "Te envío un abrazo virtual de esos que aprietan fuerte. ¡Tú puedes!",
        "Estoy enviándote toda mi energía positiva. ¡Tú puedes!"
        //
        



    ];

    // Obtenemos el día del año (de 0 a 364)
    const hoy = new Date();
    const inicioDelAnio = new Date(hoy.getFullYear(), 0, 0);
    const diff = hoy - inicioDelAnio;
    const diaDelAnio = Math.floor(diff / (1000 * 60 * 60 * 24));

    // Usamos el "módulo" (%) para ciclar los mensajes
    // Si tienes 10 mensajes, el día 11 mostrará el mensaje 1, el día 12 el 2, etc.
    const indiceMensaje = (diaDelAnio - 1) % mensajes.length;
    
    // Ponemos el mensaje en la página
    document.getElementById("mensaje-del-dia").innerText = mensajes[indiceMensaje];

    
    // --- 2. Lógica de Corazones Flotantes ---
    
    const heartContainer = document.querySelector(".heart-container");

    function crearCorazon() {
        const heart = document.createElement('div');
        heart.classList.add('heart');
        
        // Posición horizontal aleatoria
        heart.style.left = Math.random() * 100 + 'vw';
        
        // Duración de animación aleatoria (para que no suban todos iguales)
        heart.style.animationDuration = (Math.random() * 5 + 5) + 's'; // Entre 5 y 10 segundos
        
        heartContainer.appendChild(heart);
        
        // Removemos el corazón cuando termina la animación
        setTimeout(() => {
            heart.remove();
        }, 10000); // 10 segundos
    }

    // Creamos un corazón nuevo cada segundo
    setInterval(crearCorazon, 1000);
});


